const palabras = [
    "abecedario", "acertijo", "admirable", "afinado", "agradar", "ajustar",
    "albatozo", "alegría", "almohada", "amabilidad", "ambición", "anillo",
    "aplaudir", "árabe", "asfalto", "atleta", "avión", "azúcar",
    "balde", "banco", "barra", "basura", "bebida", "beduino",
    "cabeza", "café", "calor", "camisa", "casa", "cebolla",
    "celular", "cerdo", "chico", "ciudad", "clase", "colina",
    "comer", "computadora", "conductor", "copo", "corral", "costumbre",
    "cuadrado", "cuarto", "danza", "decidir", "desayuno", "diablo",
    "dibujo", "dinero", "disco", "divinidad", "domingo", "donde",
    "durante", "edad", "efectivo", "elefante", "empezar", "enfermo",
    "energía", "entender", "equipo", "escuela", "esperar", "estrella",
    "extraño", "familia", "felicidad", "flor", "frío", "galaxia",
    "gato", "generoso", "gente", "giro", "gobernar", "grande",
    "guerra", "hablar", "hambre", "harina", "hermano", "historia",
    "hogar", "hora", "hospital", "hotel", "humano", "iglesia",
    "imagen", "importante", "incendio", "independencia", "infeliz", "ingeniero",
    "jugar", "juicio", "justicia", "kilo", "laboratorio", "lápiz",
    "leche", "libro", "limpiar", "lindo", "línea", "luz",
    "maestro", "matar", "medicina", "memoria", "mesa", "miedo",
    "mil", "minuto", "modelo", "monstruo", "morir", "motor",
    "nada", "natural", "neblina", "negocio", "niño", "noche",
    "novela", "objeto", "oculto", "oficina", "ojos", "opuesto",
    "orden", "oro", "otro", "padre", "palabra", "pan",
    "parque", "parte", "pasar", "patio", "pecado", "película",
    "perder", "persona", "piensa", "plata", "plantar", "plaza",
    "poema", "política", "poner", "pueblo", "puerto", "punto",
    "querer", "rápido", "rayo", "recibir", "recordar", "refrescar",
    "regresar", "religión", "remedio", "repentir", "respirar", "rostro",
    "saber", "salir", "salud", "sandwich", "secreto", "sentimiento",
    "siempre", "silencio", "simplemente", "sin", "sitio", "soñar",
    "sonrisa", "sueño", "suelo", "superior", "surgir", "tarea",
    "temprano", "tiempo", "tinta", "tocar", "tomate", "tono",
    "trabajo", "tranquilo", "transmitir", "trauma", "tribu", "turismo",
    "último", "unirse", "utilidad", "vaca", "valiente", "valor",
    "variedad", "veloz", "ventana", "verdad", "vida", "violín",
    "volar", "voluntario", "vuelta", "yogur", "zapatilla"
];

export default palabras;